### PR TITLE
fix: not responding to touch on android #5

### PR DESCRIPTION
**Pull request by shoma-mano**
I want to use this great library in bottom-sheet, so I:

- Migrated to react-native-reanimated from react-native.
- In some UI libraries like @gorhom/bottom-sheet, [a special ScrollView is implemented to make scrolling work properly.](https://github.com/gorhom/react-native-bottom-sheet/blob/59ab3c6b88c2ccbc3fed9aa3de66bf3fbf64815a/src/components/bottomSheetScrollable/BottomSheetScrollView.tsx#L17-L20) I added a feature to replace the ScrollView with one that is compatible with such libraries.

I confirmed that all pickers in the example work as before on both Android and iOS, and I also added a picker that works in a bottom sheet. However, if this is not necessary, I will remove it.

### CODE REVIEW

**Comment by rozhkovs** [comment]
@shoma-mano thank you for the PR! Is it possible to use the `renderList` property for these purposes? As an example, you can look at `withVirtualized` HOC.

It seems to me that it is enough just to add an additional example that demonstrated how this can be adapted using `renderList` without the `reanimated`.

I also see that the animation will work on the JS side when scrolling occurs. Right? If so, the performance may be lower.

**Comment by shoma-mano** [comment]
Thanks for replying!

> renderList property for these purposes? As an example, you can look at withVirtualized HOC. 

I decided to implement it this way because I thought that all parts, except for the ScrollView, could be reused with a regular Picker, and the renderList method might be a bit difficult for users to understand. However, I believe it could be a good idea to include an example with the renderList method as a solution. 

>It seems to me that it is enough just to add an additional example that demonstrated how this can be adapted using renderList without the reanimated

Does this mean migrating itself is not necessary?

> I also see that the animation will work on the JS side when scrolling occurs. Right? If so, the performance may be lower.

How can this be verified? I apologize for my lack of knowledge.To be honest, I have experience with web development, but I'm a beginner when it comes to React Native.

**Comment by shoma-mano** [comment]
I have confirmed that an issue is occurring when scrolling quickly, which did not happen before. It seems that the migration is not as straightforward as I initially thought😂 You can go ahead and close the PR.

**Comment by rozhkovs** [comment]
@shoma-mano 
Thanks for waiting!

I see it useful to do the following: release a 2.0 library that will run on `react-native-gesture-handler` and `react-native-reanimated` by default, because Expo is the recommended framework from the react-native team, and it includes these libraries. Fewer potential gesture conflicts and more flexible animations.

However, in the context of this PR, the correction of gesture processing is implied. It seems that the big task is to immediately do the migration and provide integration with `@gorhom/bottom-sheet`

I understand that this library is really useful in the `@gorhom/bottom-sheet` bundle and I want to provide easy integration with it. 

But the problem is that so far I have found only the only good option for how to save native animation is through the `scrollEventsHandlersHook` properties in `BottomSheetScrollView`, which is experimental.

It is important to keep the native animation, because in complex applications there can be a lot of work on the part of JS and this can lead to a bad user experience.

I will try to do the migration in the coming days, weeks and provide good ways to integrate with `@gorhom/bottom-sheet` if someone else does not do it.

> How can this be verified? I apologize for my lack of knowledge.To be honest, I have experience with web development, but I'm a beginner when it comes to React Native.

You can use `console.log(‘someFunc: _WORKLET', _WORKLET)` to see if the function works from the UI and JS side for Reanimated.  

Your changes are good enough to migrate to Reanimated and GH, if you have the desire, you can open a new PR for this.

**Pull request closed without merging**
